server:
  port: 8083

spring:
  application:
    name: fake-payment-provider
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:55720/payment_provider
    username: paymentprovider
    password: paymentprovider
  flyway:
    url: jdbc:postgresql://localhost:55720/payment_provider
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /api/v1/api-docs/doc.yaml
  swagger-ui:
    path: /swagger-ui/index.html